/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OACRental;

import OACRental.UI.UI;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        UI userInterface = new UI();
        Application.launch(userInterface.getClass());
    }
}
