/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OACRental;

import OACRental.UI.UI;
import javafx.application.Application;

public class App {
    static UI userInterface;

    public static void main(String[] args) {
        userInterface = new UI();
        Application.launch(userInterface.getClass());
    }

    public static void setStyle(String styleName) {
        userInterface.setStyle(styleName);
    }
}
